---
language: python
services: docker

env:
  global:
    - MOLECULE_NO_LOG: "false"
  matrix:
    - MOLECULE_DISTRO: ubuntu:18.04

install:
  # Install test dependencies.
  - pip install molecule docker ansible-lint

before_script:
  - cd ../ && mv ansible-sleuthkit juju4.sleuthkit
  - cd juju4.sleuthkit

script:
  - molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
