---

- name: Debian | Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: pkg_result
  until: pkg_result is success

- name: Import sleuthkit
  ansible.builtin.import_tasks: sleuthkit.yml
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)

- name: Install Sleuthkit from distribution
  ansible.builtin.apt:
    name:
      - sleuthkit
      - libtsk13
      - libtsk-dev
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)
