---

- name: Include version-specific variables for Ubuntu.
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Debian | Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: pkg_result
  until: pkg_result is success

- name: Import sleuthkit
  ansible.builtin.import_tasks: sleuthkit.yml
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)

- name: Install Sleuthkit from distribution
  ansible.builtin.apt:
    name: "{{ sleuthkit_pkgs }}"
    state: present
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 20)
